### ISSUE TITLE
Experiments page is not showing any data

### ISSUE THREAD

**Issue by E-fais** [hellofaizan/hellofaizan.me#2]

**Comment by hellofaizan** [comment]
That page is still in development. I will be showing some crazy things I will do on the web on that page. Thank you

**Comment by hellofaizan** [comment]
> 

Drop a star if you liked the portfolio

**Comment by E-fais** [comment]
Better hide that link until  you finish your work. Btw nice project.

**Comment by hellofaizan** [comment]
Oo. Will do same. Thanks buddy

**Comment by hellofaizan** [comment]
There are some features that you might have not seen. Check readme for some screenshots

**Comment by hellofaizan** [comment]
![Screenshot 2023-03-11 131224.png](https://user-images.githubusercontent.com/84437051/225366527-bee08b7b-cac8-40c8-a34b-41f8592a9766.png)

**Comment by hellofaizan** [comment]
These are real time features.

**Comment by E-fais** [comment]
I am closing this issue for now. I am happy to work with you in future 👍
